# Generated by Django 2.1.3 on 2018-11-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0002_auto_20181115_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_type',
            name='asset_name',
            field=models.CharField(default='server', max_length=64),
        ),
    ]
