# Generated by Django 2.1.3 on 2018-11-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0003_asset_type_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_type',
            name='asset_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='asset_type',
            name='asset_type',
            field=models.CharField(default='server', max_length=64, unique=True),
        ),
    ]
